name: Build & Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    name: Lint & Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Commit and Push Changes (if necessary)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Apply Prettier auto-formatting"
          git push
        continue-on-error: true # Avoid failing the workflow if nothing changes

  build:
    name: Build Minified File
    needs: lint-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Minified File
        run: npm run build
        env:
          NODE_ENV: prod

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calendar-card-pro.js
          path: dist/calendar-card-pro.js

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Latest Tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Download Built File
        uses: actions/download-artifact@v4
        with:
          name: calendar-card-pro.js
          path: dist/

      - name: Generate Release Notes
        id: generate_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/calendar-card-pro.js
          tag_name: ${{ env.tag }}
          name: 'Calendar Card Pro ${{ env.tag }}'
          body: ${{ steps.generate_notes.outputs.body }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
